name: Org health report

on:
  schedule:
    - cron: "30 3 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  health-report:
    runs-on: ubuntu-latest
    env:
      ORG: phys-sims
      REPOS_DIR: /tmp/org_repos
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout .github repo
        uses: actions/checkout@v4

      - name: Ensure tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y cloc

      - name: Clone org repos
        run: |
          mkdir -p "$REPOS_DIR"
          gh repo list "$ORG" --limit 200 --json nameWithOwner --jq '.[].nameWithOwner' \
            | while read -r full; do
                repo="${full#${ORG}/}"
                target="$REPOS_DIR/$repo"
                if [ -d "$target/.git" ]; then
                  echo "already cloned: $repo"
                else
                  echo "cloning: $repo"
                  gh repo clone "$full" "$target" -- --depth=1
                fi
              done

      - name: Run cloc
        run: bash scripts/health/run_cloc.sh "$REPOS_DIR"

      - name: Generate report and profile summary
        run: python scripts/health/generate_health_report.py --org "$ORG" --repos-dir "$REPOS_DIR"

      - name: Commit report updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/HEALTH_REPORT.md profile/README.md
          if git diff --cached --quiet; then
            echo "No health changes to commit"
          else
            git commit -m "chore(health): refresh org health report"
            git push
          fi
